apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 500Mi          # requesting 500MB from 1GB PV
