apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Prabu-12/ecommerce-devops
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
