replicaCount: 2

image:
  repository: awsjarvis/ecommerce-devops
  pullPolicy: IfNotPresent
  tag: "fc193ca75570303ff6ad24e72c82d8ae4a17d225"

namespace: ecommerce

service:
  type: NodePort
  port: 80
  targetPort: 8080

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

livenessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

config:
  appEnv: "production"
  logLevel: "INFO"
